# Generated by Django 4.2.2 on 2023-06-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='is_blog',
            field=models.BooleanField(),
        ),
    ]
