# Generated by Django 4.2.2 on 2023-07-01 19:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_alter_blogs_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
